# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebdbc77c7ea53e1b5b5311cbe92a24ad06a24d9ad80cab1c6f976761239347375471c6ed3833da7b509252aae9e621542c537c2768485150e5941b03e3443915

test:
  secret_key_base: f15637575399deb040e9e73885ef68eb0802704f4cb305cbba26ae97753903cad974851bb023208d76c755bbe12875d58855e7302700d9bfd0e3034fdca6d9ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
